spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mukflix
    username: root
    password: qwer1234
  profiles:
    active: local
    include: core


