spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mukflix
    username: root
    password: qwer1234
  profiles:
    active: local
    include: core
---
spring:
  spring:
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
spring:
  jpa:
    properties.hibernate.hbm2ddl.auto : update
    showSql : true
  messages:
    basename : i18n/exception
    encoding: utf-8
  jwt:
    secret: govlepel@$&amp;